services:
  postgres:
    container_name: postgres-sql-bsn1
    image: postgres
    environment:
      POSTGRES_USER: sehsekou98
      POSTGRES_PASSWORD: password1
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: demo_db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped

networks:
  spring-demo:
    driver: bridge
volumes:
  postgres:
    driver: local